services:
  dns01mydns:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: dns01mydns
    restart: always
    hostname: dns01mydns
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    tmpfs: /tmp
    volumes:
      - type: bind
        source: ${VOL:-./Vol}
        target: /etc/letsencrypt
